### PR TITLE
Restore iml files removed in #10 (as per #9)

### PR DESCRIPTION
**Pull request by dmfs**
@lemonboston please review.

### CODE REVIEW

**Comment by lemonboston** [comment]
`.idea/modules` is still in `.gitignore`, although the `.iml` files in the folder are checked out... Sometimes I don't understand how gitignore updates become effective, it happened to me earlier that it needed another commit or marking the files explicitly, not sure. But I suppose we need to remove that line, right?

**Comment by dmfs** [comment]
Oh yeah you're right. Forgot to update .gitignore.

**Comment by dmfs** [comment]
@lemonboston updated .gitignore.

**Comment by lemonboston** [comment]
Looks good for me.

**Pull request merged**
